import { SecretRuleConfig } from './types';

export const DEFAULT_SECRET_RULES: SecretRuleConfig[] = [
  {
    id: 'aws-access-key-id',
    name: 'AWS Access Key ID',
    description: 'AWS access key pattern',
    severity: 'high',
    pattern: 'AKIA[0-9A-Z]{16}',
    flags: 'i',
    keywords: ['aws', 'access', 'key', 'id'],
  },
  {
    id: 'aws-secret-access-key',
    name: 'AWS Secret Access Key',
    description: 'AWS secret key pattern',
    severity: 'critical',
    pattern: '[A-Za-z0-9/+=]{40}',
    flags: 'g',
    keywords: ['aws', 'secret', 'access', 'key'],
  },
  {
    id: 'github-pat',
    name: 'GitHub Personal Access Token',
    description: 'GitHub PAT pattern',
    severity: 'critical',
    pattern: 'ghp_[A-Za-z0-9_]{36}',
    keywords: ['github', 'token', 'ghp_'],
  },
  {
    id: 'openai-api-key',
    name: 'OpenAI API Key',
    description: 'OpenAI API key',
    severity: 'critical',
    pattern: 'sk-[a-zA-Z0-9]{20,}',
    keywords: ['openai', 'api', 'key', 'sk-'],
  },
  {
    id: 'generic-high-entropy-base64',
    name: 'High Entropy Base64 Secret',
    description: 'Base64-like secret-like token',
    severity: 'medium',
    type: 'entropy',
    pattern: '[A-Za-z0-9+/=]{24,}',
    entropy: {
      enabled: true,
      min_length: 24,
      entropy_threshold: 4.3,
      window_size: 64,
      charset: 'base64',
    },
    keywords: ['secret', 'token', 'key', 'password', 'auth'],
  },
  {
    id: 'generic-high-entropy-hex',
    name: 'High Entropy Hex Secret',
    description: 'Hex secret-like token',
    severity: 'medium',
    type: 'entropy',
    pattern: '[A-Fa-f0-9]{32,}',
    entropy: {
      enabled: true,
      min_length: 32,
      entropy_threshold: 3.7,
      window_size: 64,
      charset: 'hex',
    },
    keywords: ['secret', 'token', 'api', 'passwd', 'credential', 'key'],
  },
  {
    id: 'private-key-marker',
    name: 'Private Key Marker',
    description: 'Private key block header',
    severity: 'critical',
    pattern: '-----BEGIN (RSA|DSA|EC|OPENSSH) PRIVATE KEY-----',
    flags: 'i',
    paths: ['*.pem', '*.key', '*.p12', '*.pkcs12', '*.jks'],
  },
];
